name: Sincronização Diária Sucão → Ancar

on:
  schedule:
    - cron: '0 11 * * *'  # Executa todos os dias às 8:00 AM Brasil
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  sync-sales:
    runs-on: ubuntu-22.04  # Versão específica do Ubuntu
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-0 \
            libnss3 \
            libnspr4 \
            libdbus-1-3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2t64 \
            libatspi2.0-0
      
      - name: Instalar programas Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      
      - name: Executar automação
        env:
          SUCAO_EMAIL: ${{ secrets.SUCAO_EMAIL }}
          SUCAO_PASSWORD: ${{ secrets.SUCAO_PASSWORD }}
          ANCAR_USERNAME: ${{ secrets.ANCAR_USERNAME }}
          ANCAR_PASSWORD: ${{ secrets.ANCAR_PASSWORD }}
          TZ: America/Sao_Paulo
          PYTHONUNBUFFERED: 1
        run: |
          echo "Starting sync_sales.py..."
          python -u sync_sales.py
